'use strict';
function execute(connection, command) { return new Promise((resolve, reject) => connection.exec(command, (error, stream) => { if (error) return reject(error); const output=[],errors=[]; stream.on('data',data=>output.push(String(data))); stream.stderr.on('data',data=>errors.push(String(data))); stream.once('error',reject).once('close',(code,signal)=>resolve({code,signal,stdout:output.join('').trimEnd(),stderr:errors.join('').trimEnd()})); })); }
function connect(credential) { const { Client } = require('ssh2'); const connection=new Client(); return new Promise((resolve,reject)=>connection.once('ready',()=>resolve(connection)).once('error',reject).connect({host:String(credential.host),port:Number(credential.port)||22,username:String(credential.username),...(credential.privateKey?{privateKey:String(credential.privateKey)}:{password:String(credential.password||'')})})); }
module.exports={
 type:'send_ssh_command',name:'Send SSH Command',category:'Server Management',description:'Runs one or more commands using a Linux SSH credential from Credential Manager.',
 inputs:[{id:'action',name:'Action',kind:'action',types:[]},{id:'credential',name:'Linux Credential',kind:'value',types:['linux_credential'],required:true},{id:'textcommand',name:'Command',kind:'value',types:['text'],required:true}],
 inputPorts:[{id:'action',name:'Action',kind:'action',types:[]},{id:'credential',name:'Linux Credential',kind:'value',types:['linux_credential'],required:true},{id:'textcommand',name:'Command',kind:'value',types:['text'],required:true},...['host','port','username','password'].map(id=>({id,name:id,kind:'value',types:id==='port'?['number']:['text'],hidden:true}))],
 fields:[],outputs:['action','erroraction'],outputPorts:[{id:'action',name:'Action',kind:'action',types:[]},{id:'erroraction',name:'Action (Error)',kind:'action',types:[]},{id:'output',name:'Output',kind:'value',types:['text']},{id:'error',name:'Error Message',kind:'value',types:['text']}],
 async execute(ctx,options,inputs,setOutput){const credential=inputs.credential||(inputs.host||options.host?{host:inputs.host||options.host,port:inputs.port||options.port,username:inputs.username||options.username,password:inputs.password||options.password}:null);if(!credential){setOutput('error','A Linux Credential is required');return'erroraction';}const commands=String(inputs.textcommand??options.textcommand??'').split(/\r?\n/).filter(line=>line.trim());let connection;try{connection=await connect(credential);const lines=[];for(const command of commands){lines.push(`${credential.username}@${credential.host}:~$ ${command.trim()}`);const result=await execute(connection,command);if(result.stdout)lines.push(result.stdout);if(result.stderr)lines.push(result.stderr);if(result.code!==0)throw new Error(`SSH command exited with code ${result.code}${result.stderr?`: ${result.stderr}`:''}`);}setOutput('output',lines.join('\n'));setOutput('error','');return'action';}catch(error){if(ctx.signal?.aborted)throw error;setOutput('error',error.message);return'erroraction';}finally{connection?.end();}},executeSSH:execute,connectSSH:connect
};
